### ISSUE TITLE
I want to crossbuild webos for an ARM SOC

### ISSUE THREAD

**Issue by rahmanih** [openwebos/build-webos#1]
Hi,
First of all congrats for this great soft!
Reading the HowTo I can't find any to crasscompile the openwebos for
other arch except x86, does the webos build system supports cross compilation 
or not yet?

regards

**Comment by ericblade** [comment]
That's exactly what this build system does.  You may want to join pop over to the IRC chat hosted on freenode.net in the channel #webOS-Ports for real time help.

**Comment by ykchoi70** [comment]
There are no more queries on this issue, so we are closing it.
