### ISSUE TITLE
Login account does not work after running qemux

### ISSUE THREAD

**Issue by hyunkim9123** [openwebos/build-webos#2]
After building qemux86, I was asked to login but have no idea of the account.
Should we add "debug-tweaks" when building? If,so am going to commit that patch.

**Comment by jinyo** [comment]
I tested with below commands,

> jinyo@cdp2:~/work/openwebos/open0814$ runqemu BUILD/deploy/images/qemux86/bzImage-qemux86.bin BUILD/deploy/images/qemux86/webos-image-qemux86.ext3 ext3 

But I can't login

> qemux86 login: root
> password : (Enter)
> Login incorrect
