### ISSUE TITLE
Can't build libpbnjson

### ISSUE THREAD

**Issue by initialjie** [openwebos/build-webos#7]
CMake Error at CMakeLists.txt:22 (include):
  include could not find load file:

    webOS/webOS

CMake Error at CMakeLists.txt:23 (webos_modules_init):
  Unknown CMake command "webos_modules_init".

-- Configuring incomplete, errors occurred!

**Comment by ykchoi70** [comment]
Please rebuild using latest version and there are no more queries on this issue, so we are closing it.
